/*******************************************************************************
 * EMF Specific API of the policy.constraint pattern
 * Generated by EMF-IncQuery
 *******************************************************************************/

package patternmatchers.policy;

import java.util.Collection;

import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IPatternSignature;
import org.eclipse.viatra2.emf.incquery.runtime.api.IMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.exception.IncQueryRuntimeException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.ReteEngine;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;

import signatures.policy.ConstraintSignature;

/**
 * Generated domain-specific pattern matcher API of of the policy.constraint pattern.
 * Please instantiate using the static field FACTORY.
 */
@SuppressWarnings("unused")
public class ConstraintMatcher extends BaseGeneratedMatcher<ConstraintSignature> implements IncQueryMatcher<ConstraintSignature>{

	public final static IMatcherFactory<ConstraintSignature,ConstraintMatcher> FACTORY = new Factory();
	public static class Factory extends BaseMatcherFactory<ConstraintSignature,ConstraintMatcher> {
			@Override
			public ConstraintMatcher instantiate(ReteEngine<String> reteEngine) throws IncQueryRuntimeException {
				return new ConstraintMatcher(reteEngine);
			}
			@Override
			public String getPatternName() {
				return "policy.constraint";
			}
		} 
			
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param CONSTRAINT the fixed value of pattern parameter CONSTRAINT, or null if not bound.
	 * @return matches represented as an array containing the values of each parameter.
	 */
	public Collection<Object[]> getAllMatchesAsArray(Object CONSTRAINT) {
		return getAllMatchesAsArray(new Object[] {CONSTRAINT});
	}
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param CONSTRAINT the fixed value of pattern parameter CONSTRAINT, or null if not bound.
	 * @return matches represented as a ConstraintSignature object.
	 */
	public Collection<ConstraintSignature> getAllMatchesAsSignature(Object CONSTRAINT) {
		return getAllMatchesAsSignature(new Object[] {CONSTRAINT});
	}

	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param CONSTRAINT the fixed value of pattern parameter CONSTRAINT, or null if not bound.
	 * @return a match represented as an array containing the values of each parameter, or null if no match is found.
	 */
	public Object[] getOneMatchAsArray(Object CONSTRAINT) {
		return getOneMatchAsArray(new Object[] {CONSTRAINT});
	}
	
	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param CONSTRAINT the fixed value of pattern parameter CONSTRAINT, or null if not bound.
	 * @return a match represented as a ConstraintSignature object, or null if no match is found.
	 */
	public ConstraintSignature getOneMatchAsSignature(Object CONSTRAINT) {
		return getOneMatchAsSignature(new Object[] {CONSTRAINT});
	}
	
	/**
	 * Indicates whether the given combination of specified pattern parameters constitute a valid pattern match,
	 * 	under any possible substitution of the unspecified parameters.
	 * @param CONSTRAINT the fixed value of pattern parameter CONSTRAINT, or null if not bound.
	 * @return true if the input is a valid (partial) match of the pattern.
	 */
	public boolean hasMatch(Object CONSTRAINT) {
		return hasMatch(new Object[] {CONSTRAINT});
	}
	
	/** 
	 * Returns the number of all pattern matches given some fixed parameters.
	 * @param CONSTRAINT the fixed value of pattern parameter CONSTRAINT, or null if not bound.
	 * @return the number of pattern matches found.
	 */	
	public int countMatches(Object CONSTRAINT) {
		return countMatches(new Object[] {CONSTRAINT});
	}
	


	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getPatternName()
	 */
	@Override
	public String getPatternName() {
		return "policy.constraint";
	}

	private static final String[] paramNames = new String[] {"CONSTRAINT"};
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getParameterNames()
	 */
	@Override
	public String[] getParameterNames() {
		return paramNames;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher#tupleToSignature(org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple)
	 */
	@Override
	protected ConstraintSignature tupleToSignature(Tuple t) {
		return new ConstraintSignature(t.get(0));
	}
	
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#arrayToSignature(java.lang.Object[])
	 */
	@Override
	public ConstraintSignature arrayToSignature(Object[] signature) {
		return new ConstraintSignature(signature[0]);
	}	
	
	private ConstraintMatcher(ReteEngine<String> engine) throws IncQueryRuntimeException {
		super(engine, "policy.constraint");
	}
		
}
