/*******************************************************************************
 * Pattern builder for pattern grapho.edge
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.grapho;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern grapho.edge
 */
public class PatternBuilderForedge implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("grapho.edge".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("grapho.edge");
		
		final Address<? extends Receiver> var_110 = buildable.patternCollector("grapho.edge");
		final Stub<Address<? extends Supplier>> var_111 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_112 = EPackage.Registry.INSTANCE.getEPackage("http://grapho/1.0").getEClassifier("Edge");
		final Stub<Address<? extends Supplier>> var_113 = buildable.unaryTypeStub(new FlatTuple(new Object[] {"EDGE"}), var_112);
		final TupleMask var_114 = new TupleMask(new int[] {}, 0);
		final TupleMask var_115 = new TupleMask(new int[] {}, 1);
		final TupleMask var_116 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_117 = buildable.buildBetaNode(var_111, var_113, var_114, var_115, var_116, false);
		final TupleMask var_118 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_119 = buildable.buildTrimmer(var_117, var_118);
		buildable.buildConnection(var_119, var_110);
		return var_110;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("grapho.edge".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("EDGE", 0);

		}
		return posMapping;
	}
}
