/*******************************************************************************
 * Pattern builder for pattern grapho.graphelement
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.grapho;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern grapho.graphelement
 */
public class PatternBuilderForgraphelement implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("grapho.graphelement".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("grapho.graphelement");
		
		final Address<? extends Receiver> var_130 = buildable.patternCollector("grapho.graphelement");
		final Stub<Address<? extends Supplier>> var_131 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_132 = EPackage.Registry.INSTANCE.getEPackage("http://grapho/1.0").getEClassifier("GraphElement");
		final Stub<Address<? extends Supplier>> var_133 = buildable.unaryTypeStub(new FlatTuple(new Object[] {"GRAPHELEMENT"}), var_132);
		final TupleMask var_134 = new TupleMask(new int[] {}, 0);
		final TupleMask var_135 = new TupleMask(new int[] {}, 1);
		final TupleMask var_136 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_137 = buildable.buildBetaNode(var_131, var_133, var_134, var_135, var_136, false);
		final TupleMask var_138 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_139 = buildable.buildTrimmer(var_137, var_138);
		buildable.buildConnection(var_139, var_130);
		return var_130;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("grapho.graphelement".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("GRAPHELEMENT", 0);

		}
		return posMapping;
	}
}
