/*******************************************************************************
 * EMF Specific API of the grapho.graphelement pattern
 * Generated by EMF-IncQuery
 *******************************************************************************/

package patternmatchers.grapho;

import java.util.Collection;

import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IPatternSignature;
import org.eclipse.viatra2.emf.incquery.runtime.api.IMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.exception.IncQueryRuntimeException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.ReteEngine;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;

import signatures.grapho.GraphelementSignature;

/**
 * Generated domain-specific pattern matcher API of of the grapho.graphelement pattern.
 * Please instantiate using the static field FACTORY.
 */
@SuppressWarnings("unused")
public class GraphelementMatcher extends BaseGeneratedMatcher<GraphelementSignature> implements IncQueryMatcher<GraphelementSignature>{

	public final static IMatcherFactory<GraphelementSignature,GraphelementMatcher> FACTORY = new Factory();
	public static class Factory extends BaseMatcherFactory<GraphelementSignature,GraphelementMatcher> {
			@Override
			public GraphelementMatcher instantiate(ReteEngine<String> reteEngine) throws IncQueryRuntimeException {
				return new GraphelementMatcher(reteEngine);
			}
			@Override
			public String getPatternName() {
				return "grapho.graphelement";
			}
		} 
			
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param GRAPHELEMENT the fixed value of pattern parameter GRAPHELEMENT, or null if not bound.
	 * @return matches represented as an array containing the values of each parameter.
	 */
	public Collection<Object[]> getAllMatchesAsArray(Object GRAPHELEMENT) {
		return getAllMatchesAsArray(new Object[] {GRAPHELEMENT});
	}
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param GRAPHELEMENT the fixed value of pattern parameter GRAPHELEMENT, or null if not bound.
	 * @return matches represented as a GraphelementSignature object.
	 */
	public Collection<GraphelementSignature> getAllMatchesAsSignature(Object GRAPHELEMENT) {
		return getAllMatchesAsSignature(new Object[] {GRAPHELEMENT});
	}

	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param GRAPHELEMENT the fixed value of pattern parameter GRAPHELEMENT, or null if not bound.
	 * @return a match represented as an array containing the values of each parameter, or null if no match is found.
	 */
	public Object[] getOneMatchAsArray(Object GRAPHELEMENT) {
		return getOneMatchAsArray(new Object[] {GRAPHELEMENT});
	}
	
	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param GRAPHELEMENT the fixed value of pattern parameter GRAPHELEMENT, or null if not bound.
	 * @return a match represented as a GraphelementSignature object, or null if no match is found.
	 */
	public GraphelementSignature getOneMatchAsSignature(Object GRAPHELEMENT) {
		return getOneMatchAsSignature(new Object[] {GRAPHELEMENT});
	}
	
	/**
	 * Indicates whether the given combination of specified pattern parameters constitute a valid pattern match,
	 * 	under any possible substitution of the unspecified parameters.
	 * @param GRAPHELEMENT the fixed value of pattern parameter GRAPHELEMENT, or null if not bound.
	 * @return true if the input is a valid (partial) match of the pattern.
	 */
	public boolean hasMatch(Object GRAPHELEMENT) {
		return hasMatch(new Object[] {GRAPHELEMENT});
	}
	
	/** 
	 * Returns the number of all pattern matches given some fixed parameters.
	 * @param GRAPHELEMENT the fixed value of pattern parameter GRAPHELEMENT, or null if not bound.
	 * @return the number of pattern matches found.
	 */	
	public int countMatches(Object GRAPHELEMENT) {
		return countMatches(new Object[] {GRAPHELEMENT});
	}
	


	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getPatternName()
	 */
	@Override
	public String getPatternName() {
		return "grapho.graphelement";
	}

	private static final String[] paramNames = new String[] {"GRAPHELEMENT"};
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getParameterNames()
	 */
	@Override
	public String[] getParameterNames() {
		return paramNames;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher#tupleToSignature(org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple)
	 */
	@Override
	protected GraphelementSignature tupleToSignature(Tuple t) {
		return new GraphelementSignature(t.get(0));
	}
	
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#arrayToSignature(java.lang.Object[])
	 */
	@Override
	public GraphelementSignature arrayToSignature(Object[] signature) {
		return new GraphelementSignature(signature[0]);
	}	
	
	private GraphelementMatcher(ReteEngine<String> engine) throws IncQueryRuntimeException {
		super(engine, "grapho.graphelement");
	}
		
}
