/*******************************************************************************
 * Pattern builder for pattern policy.session
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.policy;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern policy.session
 */
public class PatternBuilderForsession implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("policy.session".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("policy.session");
		
		final Address<? extends Receiver> var_80 = buildable.patternCollector("policy.session");
		final Stub<Address<? extends Supplier>> var_81 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_82 = EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("Session");
		final Stub<Address<? extends Supplier>> var_83 = buildable.unaryTypeStub(new FlatTuple(new Object[] {"SESSION"}), var_82);
		final TupleMask var_84 = new TupleMask(new int[] {}, 0);
		final TupleMask var_85 = new TupleMask(new int[] {}, 1);
		final TupleMask var_86 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_87 = buildable.buildBetaNode(var_81, var_83, var_84, var_85, var_86, false);
		final TupleMask var_88 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_89 = buildable.buildTrimmer(var_87, var_88);
		buildable.buildConnection(var_89, var_80);
		return var_80;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("policy.session".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("SESSION", 0);

		}
		return posMapping;
	}
}
