/*******************************************************************************
 * Pattern builder for pattern policy.policyelement
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.policy;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern policy.policyelement
 */
public class PatternBuilderForpolicyelement implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("policy.policyelement".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("policy.policyelement");
		
		final Address<? extends Receiver> var_120 = buildable.patternCollector("policy.policyelement");
		final Stub<Address<? extends Supplier>> var_121 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_122 = EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("PolicyElement");
		final Stub<Address<? extends Supplier>> var_123 = buildable.unaryTypeStub(new FlatTuple(new Object[] {"POLICYELEMENT"}), var_122);
		final TupleMask var_124 = new TupleMask(new int[] {}, 0);
		final TupleMask var_125 = new TupleMask(new int[] {}, 1);
		final TupleMask var_126 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_127 = buildable.buildBetaNode(var_121, var_123, var_124, var_125, var_126, false);
		final TupleMask var_128 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_129 = buildable.buildTrimmer(var_127, var_128);
		buildable.buildConnection(var_129, var_120);
		return var_120;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("policy.policyelement".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("POLICYELEMENT", 0);

		}
		return posMapping;
	}
}
