/*******************************************************************************
 * Pattern builder for pattern policy.object
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.policy;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern policy.object
 */
public class PatternBuilderForobject implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("policy.object".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("policy.object");
		
		final Address<? extends Receiver> var_90 = buildable.patternCollector("policy.object");
		final Stub<Address<? extends Supplier>> var_91 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_92 = EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("Object");
		final Stub<Address<? extends Supplier>> var_93 = buildable.unaryTypeStub(new FlatTuple(new Object[] {"OBJECT"}), var_92);
		final TupleMask var_94 = new TupleMask(new int[] {}, 0);
		final TupleMask var_95 = new TupleMask(new int[] {}, 1);
		final TupleMask var_96 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_97 = buildable.buildBetaNode(var_91, var_93, var_94, var_95, var_96, false);
		final TupleMask var_98 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_99 = buildable.buildTrimmer(var_97, var_98);
		buildable.buildConnection(var_99, var_90);
		return var_90;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("policy.object".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("OBJECT", 0);

		}
		return posMapping;
	}
}
