/*******************************************************************************
 * Pattern builder for pattern policy.constraint
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.policy;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern policy.constraint
 */
public class PatternBuilderForconstraint implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("policy.constraint".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("policy.constraint");
		
		final Address<? extends Receiver> var_30 = buildable.patternCollector("policy.constraint");
		final Stub<Address<? extends Supplier>> var_31 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_32 = EPackage.Registry.INSTANCE.getEPackage("http://policy/1.0").getEClassifier("Constraint");
		final Stub<Address<? extends Supplier>> var_33 = buildable.unaryTypeStub(new FlatTuple(new Object[] {"CONSTRAINT"}), var_32);
		final TupleMask var_34 = new TupleMask(new int[] {}, 0);
		final TupleMask var_35 = new TupleMask(new int[] {}, 1);
		final TupleMask var_36 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_37 = buildable.buildBetaNode(var_31, var_33, var_34, var_35, var_36, false);
		final TupleMask var_38 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_39 = buildable.buildTrimmer(var_37, var_38);
		buildable.buildConnection(var_39, var_30);
		return var_30;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("policy.constraint".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("CONSTRAINT", 0);

		}
		return posMapping;
	}
}
